### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Chocobo1**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
@Balls0fSteel this was merged 7 hours before this comment. However, the site isn't updated. Are you sure your script works?

**Comment by Chocobo1** [comment]
Haven't merge this PR yet...

**Comment by sledgehammer999** [comment]
>I haven't merged this PR yet...

Sorry, I just opened it via the email link and I thought I saw "merged" status.

**Comment by Balls0fSteel** [comment]
Phew I started panicking when I read your tag Sledge. 
So is everything alright @Chocobo1 ?

**Comment by Chocobo1** [comment]
> So is everything alright @Chocobo1 ?

Everything is fine.

**Pull request merged**
